/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : User } |
  { 'err' : string };
export interface ChatMessage {
  'id' : MessageId,
  'body' : string,
  'senderUsername' : string,
  'sender' : UserId,
  'timestamp' : Timestamp,
}
export interface FriendRequest {
  'status' : FriendRequestStatus,
  'toUsername' : string,
  'timestamp' : Timestamp,
  'fromUsername' : string,
}
export type FriendRequestStatus = { 'Rejected' : null } |
  { 'Accepted' : null } |
  { 'Pending' : null };
export interface Mail {
  'id' : MailId,
  'subject' : string,
  'body' : string,
  'senderUsername' : string,
  'isRead' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'recipientUsername' : string,
}
export type MailId = bigint;
export interface MailInput {
  'subject' : string,
  'body' : string,
  'recipientUsername' : string,
}
export type MailResult = { 'ok' : Mail } |
  { 'err' : string };
export type MessageId = bigint;
export interface Note {
  'id' : NoteId,
  'title' : string,
  'ownerId' : UserId,
  'body' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type NoteId = bigint;
export interface NoteInput { 'title' : string, 'body' : string }
export type NoteResult = { 'ok' : Note } |
  { 'err' : string };
export interface PrivateMessage {
  'id' : PrivateMessageId,
  'body' : string,
  'isRead' : boolean,
  'toUsername' : string,
  'timestamp' : Timestamp,
  'fromUsername' : string,
}
export type PrivateMessageId = bigint;
export interface ProfileUpdate {
  'bio' : string,
  'username' : string,
  'biography' : string,
  'textPlate' : [] | [TextPlate],
  'usernameEffect' : UsernameEffect,
  'avatarUrl' : string,
}
export type Role = { 'User' : null } |
  { 'Admin' : null } |
  { 'Owner' : null };
export type TextPlate = { 'Neon' : null } |
  { 'None' : null } |
  { 'MatrixPurple' : null } |
  { 'MatrixRed' : null } |
  { 'ScanlinesPlate' : null } |
  { 'FirePlate' : null } |
  { 'MatrixBlue' : null } |
  { 'MatrixPink' : null } |
  { 'Galaxy' : null } |
  { 'LavaPlate' : null } |
  { 'MatrixYellow' : null } |
  { 'ElectricPlate' : null } |
  { 'Rainbow' : null } |
  { 'MatrixGreen' : null } |
  { 'AuroraPlate' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'role' : Role,
  'biography' : string,
  'isOnline' : boolean,
  'textPlate' : TextPlate,
  'usernameEffect' : UsernameEffect,
  'avatarUrl' : string,
  'lastSeen' : Timestamp,
}
export type UserId = Principal;
export type UsernameEffect = { 'Ice' : null } |
  { 'Fire' : null } |
  { 'Gold' : null } |
  { 'Neon' : null } |
  { 'None' : null } |
  { 'MatrixRed' : null } |
  { 'Shadow' : null } |
  { 'MatrixBlue' : null } |
  { 'Cyberpunk' : null } |
  { 'Glitch' : null } |
  { 'Rainbow' : null } |
  { 'MatrixGreen' : null };
export interface _SERVICE {
  'acceptFriendRequest' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createNote' : ActorMethod<[NoteInput], NoteResult>,
  'deleteNote' : ActorMethod<[NoteId], { 'ok' : null } | { 'err' : string }>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getFriends' : ActorMethod<[], Array<User>>,
  'getInbox' : ActorMethod<[], Array<Mail>>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getPrivateMessages' : ActorMethod<[string], Array<PrivateMessage>>,
  'getProfile' : ActorMethod<[UserId], [] | [User]>,
  'getSent' : ActorMethod<[], Array<Mail>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'login' : ActorMethod<[string], AuthResult>,
  'markPrivateMessageRead' : ActorMethod<
    [PrivateMessageId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markRead' : ActorMethod<[MailId], { 'ok' : null } | { 'err' : string }>,
  'ping' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[string, string], AuthResult>,
  'rejectFriendRequest' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendFriendRequest' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendMail' : ActorMethod<[MailInput], MailResult>,
  'sendMessage' : ActorMethod<
    [string],
    { 'ok' : ChatMessage } |
      { 'err' : string }
  >,
  'sendPrivateMessage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTextPlate' : ActorMethod<
    [string, TextPlate],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setUserRole' : ActorMethod<
    [string, Role],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setUsernameEffect' : ActorMethod<
    [string, UsernameEffect],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateNote' : ActorMethod<[NoteId, NoteInput], NoteResult>,
  'updateProfile' : ActorMethod<[ProfileUpdate], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];