/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoteInput = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });
export const NoteId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const NoteResult = IDL.Variant({ 'ok' : Note, 'err' : IDL.Text });
export const FriendRequestStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'status' : FriendRequestStatus,
  'toUsername' : IDL.Text,
  'timestamp' : Timestamp,
  'fromUsername' : IDL.Text,
});
export const Role = IDL.Variant({
  'User' : IDL.Null,
  'Admin' : IDL.Null,
  'Owner' : IDL.Null,
});
export const TextPlate = IDL.Variant({
  'Neon' : IDL.Null,
  'None' : IDL.Null,
  'MatrixPurple' : IDL.Null,
  'MatrixRed' : IDL.Null,
  'ScanlinesPlate' : IDL.Null,
  'FirePlate' : IDL.Null,
  'MatrixBlue' : IDL.Null,
  'MatrixPink' : IDL.Null,
  'Galaxy' : IDL.Null,
  'LavaPlate' : IDL.Null,
  'MatrixYellow' : IDL.Null,
  'ElectricPlate' : IDL.Null,
  'Rainbow' : IDL.Null,
  'MatrixGreen' : IDL.Null,
  'AuroraPlate' : IDL.Null,
});
export const UsernameEffect = IDL.Variant({
  'Ice' : IDL.Null,
  'Fire' : IDL.Null,
  'Gold' : IDL.Null,
  'Neon' : IDL.Null,
  'None' : IDL.Null,
  'MatrixRed' : IDL.Null,
  'Shadow' : IDL.Null,
  'MatrixBlue' : IDL.Null,
  'Cyberpunk' : IDL.Null,
  'Glitch' : IDL.Null,
  'Rainbow' : IDL.Null,
  'MatrixGreen' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'role' : Role,
  'biography' : IDL.Text,
  'isOnline' : IDL.Bool,
  'textPlate' : TextPlate,
  'usernameEffect' : UsernameEffect,
  'avatarUrl' : IDL.Text,
  'lastSeen' : Timestamp,
});
export const MailId = IDL.Nat;
export const Mail = IDL.Record({
  'id' : MailId,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'senderUsername' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'recipientUsername' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'body' : IDL.Text,
  'senderUsername' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Timestamp,
});
export const PrivateMessageId = IDL.Nat;
export const PrivateMessage = IDL.Record({
  'id' : PrivateMessageId,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'toUsername' : IDL.Text,
  'timestamp' : Timestamp,
  'fromUsername' : IDL.Text,
});
export const AuthResult = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const MailInput = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'recipientUsername' : IDL.Text,
});
export const MailResult = IDL.Variant({ 'ok' : Mail, 'err' : IDL.Text });
export const ProfileUpdate = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'biography' : IDL.Text,
  'textPlate' : IDL.Opt(TextPlate),
  'usernameEffect' : UsernameEffect,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'acceptFriendRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createNote' : IDL.Func([NoteInput], [NoteResult], []),
  'deleteNote' : IDL.Func(
      [NoteId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getPrivateMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getSent' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'login' : IDL.Func([IDL.Text], [AuthResult], []),
  'markPrivateMessageRead' : IDL.Func(
      [PrivateMessageId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markRead' : IDL.Func(
      [MailId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'ping' : IDL.Func([], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'rejectFriendRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendFriendRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendMail' : IDL.Func([MailInput], [MailResult], []),
  'sendMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendPrivateMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setTextPlate' : IDL.Func(
      [IDL.Text, TextPlate],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUserRole' : IDL.Func(
      [IDL.Text, Role],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUsernameEffect' : IDL.Func(
      [IDL.Text, UsernameEffect],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateNote' : IDL.Func([NoteId, NoteInput], [NoteResult], []),
  'updateProfile' : IDL.Func([ProfileUpdate], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoteInput = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });
  const NoteId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const NoteResult = IDL.Variant({ 'ok' : Note, 'err' : IDL.Text });
  const FriendRequestStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'status' : FriendRequestStatus,
    'toUsername' : IDL.Text,
    'timestamp' : Timestamp,
    'fromUsername' : IDL.Text,
  });
  const Role = IDL.Variant({
    'User' : IDL.Null,
    'Admin' : IDL.Null,
    'Owner' : IDL.Null,
  });
  const TextPlate = IDL.Variant({
    'Neon' : IDL.Null,
    'None' : IDL.Null,
    'MatrixPurple' : IDL.Null,
    'MatrixRed' : IDL.Null,
    'ScanlinesPlate' : IDL.Null,
    'FirePlate' : IDL.Null,
    'MatrixBlue' : IDL.Null,
    'MatrixPink' : IDL.Null,
    'Galaxy' : IDL.Null,
    'LavaPlate' : IDL.Null,
    'MatrixYellow' : IDL.Null,
    'ElectricPlate' : IDL.Null,
    'Rainbow' : IDL.Null,
    'MatrixGreen' : IDL.Null,
    'AuroraPlate' : IDL.Null,
  });
  const UsernameEffect = IDL.Variant({
    'Ice' : IDL.Null,
    'Fire' : IDL.Null,
    'Gold' : IDL.Null,
    'Neon' : IDL.Null,
    'None' : IDL.Null,
    'MatrixRed' : IDL.Null,
    'Shadow' : IDL.Null,
    'MatrixBlue' : IDL.Null,
    'Cyberpunk' : IDL.Null,
    'Glitch' : IDL.Null,
    'Rainbow' : IDL.Null,
    'MatrixGreen' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'role' : Role,
    'biography' : IDL.Text,
    'isOnline' : IDL.Bool,
    'textPlate' : TextPlate,
    'usernameEffect' : UsernameEffect,
    'avatarUrl' : IDL.Text,
    'lastSeen' : Timestamp,
  });
  const MailId = IDL.Nat;
  const Mail = IDL.Record({
    'id' : MailId,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'senderUsername' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'recipientUsername' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'body' : IDL.Text,
    'senderUsername' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Timestamp,
  });
  const PrivateMessageId = IDL.Nat;
  const PrivateMessage = IDL.Record({
    'id' : PrivateMessageId,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'toUsername' : IDL.Text,
    'timestamp' : Timestamp,
    'fromUsername' : IDL.Text,
  });
  const AuthResult = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const MailInput = IDL.Record({
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'recipientUsername' : IDL.Text,
  });
  const MailResult = IDL.Variant({ 'ok' : Mail, 'err' : IDL.Text });
  const ProfileUpdate = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'biography' : IDL.Text,
    'textPlate' : IDL.Opt(TextPlate),
    'usernameEffect' : UsernameEffect,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'acceptFriendRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createNote' : IDL.Func([NoteInput], [NoteResult], []),
    'deleteNote' : IDL.Func(
        [NoteId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getPrivateMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getSent' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'login' : IDL.Func([IDL.Text], [AuthResult], []),
    'markPrivateMessageRead' : IDL.Func(
        [PrivateMessageId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markRead' : IDL.Func(
        [MailId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'ping' : IDL.Func([], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'rejectFriendRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendFriendRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendMail' : IDL.Func([MailInput], [MailResult], []),
    'sendMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendPrivateMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setTextPlate' : IDL.Func(
        [IDL.Text, TextPlate],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUserRole' : IDL.Func(
        [IDL.Text, Role],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUsernameEffect' : IDL.Func(
        [IDL.Text, UsernameEffect],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateNote' : IDL.Func([NoteId, NoteInput], [NoteResult], []),
    'updateProfile' : IDL.Func([ProfileUpdate], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };