/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Mail {
    id: MailId;
    subject: string;
    body: string;
    senderUsername: string;
    isRead: boolean;
    sender: UserId;
    sentAt: Timestamp;
    recipientUsername: string;
}
export type NoteId = bigint;
export type Timestamp = bigint;
export interface ProfileUpdate {
    bio: string;
    username: string;
    biography: string;
    textPlate?: TextPlate;
    usernameEffect: UsernameEffect;
    avatarUrl: string;
}
export type NoteResult = {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    bio: string;
    username: string;
    role: Role;
    biography: string;
    isOnline: boolean;
    textPlate: TextPlate;
    usernameEffect: UsernameEffect;
    avatarUrl: string;
    lastSeen: Timestamp;
}
export type PrivateMessageId = bigint;
export interface MailInput {
    subject: string;
    body: string;
    recipientUsername: string;
}
export interface PrivateMessage {
    id: PrivateMessageId;
    body: string;
    isRead: boolean;
    toUsername: string;
    timestamp: Timestamp;
    fromUsername: string;
}
export type UserId = Principal;
export interface NoteInput {
    title: string;
    body: string;
}
export type MailId = bigint;
export type MessageId = bigint;
export interface FriendRequest {
    status: FriendRequestStatus;
    toUsername: string;
    timestamp: Timestamp;
    fromUsername: string;
}
export type MailResult = {
    __kind__: "ok";
    ok: Mail;
} | {
    __kind__: "err";
    err: string;
};
export interface ChatMessage {
    id: MessageId;
    body: string;
    senderUsername: string;
    sender: UserId;
    timestamp: Timestamp;
}
export type AuthResult = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export interface Note {
    id: NoteId;
    title: string;
    ownerId: UserId;
    body: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export enum FriendRequestStatus {
    Rejected = "Rejected",
    Accepted = "Accepted",
    Pending = "Pending"
}
export enum Role {
    User = "User",
    Admin = "Admin",
    Owner = "Owner"
}
export enum TextPlate {
    Neon = "Neon",
    None = "None",
    MatrixPurple = "MatrixPurple",
    MatrixRed = "MatrixRed",
    ScanlinesPlate = "ScanlinesPlate",
    FirePlate = "FirePlate",
    MatrixBlue = "MatrixBlue",
    MatrixPink = "MatrixPink",
    Galaxy = "Galaxy",
    LavaPlate = "LavaPlate",
    MatrixYellow = "MatrixYellow",
    ElectricPlate = "ElectricPlate",
    Rainbow = "Rainbow",
    MatrixGreen = "MatrixGreen",
    AuroraPlate = "AuroraPlate"
}
export enum UsernameEffect {
    Ice = "Ice",
    Fire = "Fire",
    Gold = "Gold",
    Neon = "Neon",
    None = "None",
    MatrixRed = "MatrixRed",
    Shadow = "Shadow",
    MatrixBlue = "MatrixBlue",
    Cyberpunk = "Cyberpunk",
    Glitch = "Glitch",
    Rainbow = "Rainbow",
    MatrixGreen = "MatrixGreen"
}
export interface backendInterface {
    acceptFriendRequest(fromUsername: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createNote(input: NoteInput): Promise<NoteResult>;
    deleteNote(id: NoteId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getFriends(): Promise<Array<User>>;
    getInbox(): Promise<Array<Mail>>;
    getMessages(limit: bigint): Promise<Array<ChatMessage>>;
    getNote(id: NoteId): Promise<Note | null>;
    getNotes(): Promise<Array<Note>>;
    getPrivateMessages(withUsername: string): Promise<Array<PrivateMessage>>;
    getProfile(id: UserId): Promise<User | null>;
    getSent(): Promise<Array<Mail>>;
    listUsers(): Promise<Array<User>>;
    login(passwordHash: string): Promise<AuthResult>;
    markPrivateMessageRead(id: PrivateMessageId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markRead(id: MailId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    ping(): Promise<void>;
    register(username: string, passwordHash: string): Promise<AuthResult>;
    rejectFriendRequest(fromUsername: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendFriendRequest(toUsername: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendMail(input: MailInput): Promise<MailResult>;
    sendMessage(body: string): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendPrivateMessage(toUsername: string, body: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setTextPlate(targetUsername: string, plate: TextPlate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setUserRole(targetUsername: string, role: Role): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setUsernameEffect(targetUsername: string, effect: UsernameEffect): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateNote(id: NoteId, input: NoteInput): Promise<NoteResult>;
    updateProfile(update: ProfileUpdate): Promise<AuthResult>;
}
import type { AuthResult as _AuthResult, ChatMessage as _ChatMessage, FriendRequest as _FriendRequest, FriendRequestStatus as _FriendRequestStatus, Mail as _Mail, MailResult as _MailResult, Note as _Note, NoteResult as _NoteResult, ProfileUpdate as _ProfileUpdate, Role as _Role, TextPlate as _TextPlate, Timestamp as _Timestamp, User as _User, UserId as _UserId, UsernameEffect as _UsernameEffect } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptFriendRequest(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: NoteInput): Promise<NoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0);
                return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0);
            return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: NoteId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInbox(): Promise<Array<Mail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return result;
        }
    }
    async getMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getNote(arg0: NoteId): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return result;
        }
    }
    async getPrivateMessages(arg0: string): Promise<Array<PrivateMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrivateMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrivateMessages(arg0);
            return result;
        }
    }
    async getProfile(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSent(): Promise<Array<Mail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSent();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPrivateMessageRead(arg0: PrivateMessageId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markPrivateMessageRead(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPrivateMessageRead(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRead(arg0: MailId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markRead(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRead(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async ping(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ping();
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectFriendRequest(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMail(arg0: MailInput): Promise<MailResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMail(arg0);
                return from_candid_MailResult_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMail(arg0);
            return from_candid_MailResult_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendPrivateMessage(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPrivateMessage(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPrivateMessage(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTextPlate(arg0: string, arg1: TextPlate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setTextPlate(arg0, to_candid_TextPlate_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTextPlate(arg0, to_candid_TextPlate_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: string, arg1: Role): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUsernameEffect(arg0: string, arg1: UsernameEffect): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsernameEffect(arg0, to_candid_UsernameEffect_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsernameEffect(arg0, to_candid_UsernameEffect_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: NoteId, arg1: NoteInput): Promise<NoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1);
                return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1);
            return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: ProfileUpdate): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AuthResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequestStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequestStatus): FriendRequestStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_MailResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MailResult): MailResult {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_NoteResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteResult): NoteResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TextPlate_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextPlate): TextPlate {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_User_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UsernameEffect_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsernameEffect): UsernameEffect {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    username: string;
    role: _Role;
    biography: string;
    isOnline: boolean;
    textPlate: _TextPlate;
    usernameEffect: _UsernameEffect;
    avatarUrl: string;
    lastSeen: _Timestamp;
}): {
    id: UserId;
    bio: string;
    username: string;
    role: Role;
    biography: string;
    isOnline: boolean;
    textPlate: TextPlate;
    usernameEffect: UsernameEffect;
    avatarUrl: string;
    lastSeen: Timestamp;
} {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        role: from_candid_Role_n12(_uploadFile, _downloadFile, value.role),
        biography: value.biography,
        isOnline: value.isOnline,
        textPlate: from_candid_TextPlate_n14(_uploadFile, _downloadFile, value.textPlate),
        usernameEffect: from_candid_UsernameEffect_n16(_uploadFile, _downloadFile, value.usernameEffect),
        avatarUrl: value.avatarUrl,
        lastSeen: value.lastSeen
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FriendRequestStatus;
    toUsername: string;
    timestamp: _Timestamp;
    fromUsername: string;
}): {
    status: FriendRequestStatus;
    toUsername: string;
    timestamp: Timestamp;
    fromUsername: string;
} {
    return {
        status: from_candid_FriendRequestStatus_n7(_uploadFile, _downloadFile, value.status),
        toUsername: value.toUsername,
        timestamp: value.timestamp,
        fromUsername: value.fromUsername
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    User: null;
} | {
    Admin: null;
} | {
    Owner: null;
}): Role {
    return "User" in value ? Role.User : "Admin" in value ? Role.Admin : "Owner" in value ? Role.Owner : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Neon: null;
} | {
    None: null;
} | {
    MatrixPurple: null;
} | {
    MatrixRed: null;
} | {
    ScanlinesPlate: null;
} | {
    FirePlate: null;
} | {
    MatrixBlue: null;
} | {
    MatrixPink: null;
} | {
    Galaxy: null;
} | {
    LavaPlate: null;
} | {
    MatrixYellow: null;
} | {
    ElectricPlate: null;
} | {
    Rainbow: null;
} | {
    MatrixGreen: null;
} | {
    AuroraPlate: null;
}): TextPlate {
    return "Neon" in value ? TextPlate.Neon : "None" in value ? TextPlate.None : "MatrixPurple" in value ? TextPlate.MatrixPurple : "MatrixRed" in value ? TextPlate.MatrixRed : "ScanlinesPlate" in value ? TextPlate.ScanlinesPlate : "FirePlate" in value ? TextPlate.FirePlate : "MatrixBlue" in value ? TextPlate.MatrixBlue : "MatrixPink" in value ? TextPlate.MatrixPink : "Galaxy" in value ? TextPlate.Galaxy : "LavaPlate" in value ? TextPlate.LavaPlate : "MatrixYellow" in value ? TextPlate.MatrixYellow : "ElectricPlate" in value ? TextPlate.ElectricPlate : "Rainbow" in value ? TextPlate.Rainbow : "MatrixGreen" in value ? TextPlate.MatrixGreen : "AuroraPlate" in value ? TextPlate.AuroraPlate : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ice: null;
} | {
    Fire: null;
} | {
    Gold: null;
} | {
    Neon: null;
} | {
    None: null;
} | {
    MatrixRed: null;
} | {
    Shadow: null;
} | {
    MatrixBlue: null;
} | {
    Cyberpunk: null;
} | {
    Glitch: null;
} | {
    Rainbow: null;
} | {
    MatrixGreen: null;
}): UsernameEffect {
    return "Ice" in value ? UsernameEffect.Ice : "Fire" in value ? UsernameEffect.Fire : "Gold" in value ? UsernameEffect.Gold : "Neon" in value ? UsernameEffect.Neon : "None" in value ? UsernameEffect.None : "MatrixRed" in value ? UsernameEffect.MatrixRed : "Shadow" in value ? UsernameEffect.Shadow : "MatrixBlue" in value ? UsernameEffect.MatrixBlue : "Cyberpunk" in value ? UsernameEffect.Cyberpunk : "Glitch" in value ? UsernameEffect.Glitch : "Rainbow" in value ? UsernameEffect.Rainbow : "MatrixGreen" in value ? UsernameEffect.MatrixGreen : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Mail;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Mail;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatMessage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChatMessage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Note;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
}): FriendRequestStatus {
    return "Rejected" in value ? FriendRequestStatus.Rejected : "Accepted" in value ? FriendRequestStatus.Accepted : "Pending" in value ? FriendRequestStatus.Pending : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ProfileUpdate_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileUpdate): _ProfileUpdate {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_TextPlate_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextPlate): _TextPlate {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UsernameEffect_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsernameEffect): _UsernameEffect {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    biography: string;
    textPlate?: TextPlate;
    usernameEffect: UsernameEffect;
    avatarUrl: string;
}): {
    bio: string;
    username: string;
    biography: string;
    textPlate: [] | [_TextPlate];
    usernameEffect: _UsernameEffect;
    avatarUrl: string;
} {
    return {
        bio: value.bio,
        username: value.username,
        biography: value.biography,
        textPlate: value.textPlate ? candid_some(to_candid_TextPlate_n25(_uploadFile, _downloadFile, value.textPlate)) : candid_none(),
        usernameEffect: to_candid_UsernameEffect_n29(_uploadFile, _downloadFile, value.usernameEffect),
        avatarUrl: value.avatarUrl
    };
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextPlate): {
    Neon: null;
} | {
    None: null;
} | {
    MatrixPurple: null;
} | {
    MatrixRed: null;
} | {
    ScanlinesPlate: null;
} | {
    FirePlate: null;
} | {
    MatrixBlue: null;
} | {
    MatrixPink: null;
} | {
    Galaxy: null;
} | {
    LavaPlate: null;
} | {
    MatrixYellow: null;
} | {
    ElectricPlate: null;
} | {
    Rainbow: null;
} | {
    MatrixGreen: null;
} | {
    AuroraPlate: null;
} {
    return value == TextPlate.Neon ? {
        Neon: null
    } : value == TextPlate.None ? {
        None: null
    } : value == TextPlate.MatrixPurple ? {
        MatrixPurple: null
    } : value == TextPlate.MatrixRed ? {
        MatrixRed: null
    } : value == TextPlate.ScanlinesPlate ? {
        ScanlinesPlate: null
    } : value == TextPlate.FirePlate ? {
        FirePlate: null
    } : value == TextPlate.MatrixBlue ? {
        MatrixBlue: null
    } : value == TextPlate.MatrixPink ? {
        MatrixPink: null
    } : value == TextPlate.Galaxy ? {
        Galaxy: null
    } : value == TextPlate.LavaPlate ? {
        LavaPlate: null
    } : value == TextPlate.MatrixYellow ? {
        MatrixYellow: null
    } : value == TextPlate.ElectricPlate ? {
        ElectricPlate: null
    } : value == TextPlate.Rainbow ? {
        Rainbow: null
    } : value == TextPlate.MatrixGreen ? {
        MatrixGreen: null
    } : value == TextPlate.AuroraPlate ? {
        AuroraPlate: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    User: null;
} | {
    Admin: null;
} | {
    Owner: null;
} {
    return value == Role.User ? {
        User: null
    } : value == Role.Admin ? {
        Admin: null
    } : value == Role.Owner ? {
        Owner: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsernameEffect): {
    Ice: null;
} | {
    Fire: null;
} | {
    Gold: null;
} | {
    Neon: null;
} | {
    None: null;
} | {
    MatrixRed: null;
} | {
    Shadow: null;
} | {
    MatrixBlue: null;
} | {
    Cyberpunk: null;
} | {
    Glitch: null;
} | {
    Rainbow: null;
} | {
    MatrixGreen: null;
} {
    return value == UsernameEffect.Ice ? {
        Ice: null
    } : value == UsernameEffect.Fire ? {
        Fire: null
    } : value == UsernameEffect.Gold ? {
        Gold: null
    } : value == UsernameEffect.Neon ? {
        Neon: null
    } : value == UsernameEffect.None ? {
        None: null
    } : value == UsernameEffect.MatrixRed ? {
        MatrixRed: null
    } : value == UsernameEffect.Shadow ? {
        Shadow: null
    } : value == UsernameEffect.MatrixBlue ? {
        MatrixBlue: null
    } : value == UsernameEffect.Cyberpunk ? {
        Cyberpunk: null
    } : value == UsernameEffect.Glitch ? {
        Glitch: null
    } : value == UsernameEffect.Rainbow ? {
        Rainbow: null
    } : value == UsernameEffect.MatrixGreen ? {
        MatrixGreen: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
